repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=10000' ]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.4.0
#    hooks:
#      - id: pyupgrade
#        entry: pyupgrade --py38-plus
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix .
        language: system
        pass_filenames: false
      - id: format
        name: format
        entry: ruff format
        language: system
        pass_filenames: false
      - id: format-docs
        name: format docs
        entry: blacken-docs
        language: system
        pass_filenames: true
        files: "\\.(md)$"
      - id: basedpyright
        name: basedpyright
        entry: basedpyright --level error
        language: system
        pass_filenames: false
