name: Deploy Docs Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    name: Deploy docs preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.12
          enable-cache: true

      - name: Set up Python
        if: github.event.action != 'closed'
        run: uv python install 3.12 && uv python pin 3.12

      - name: Build docs
        if: github.event.action != 'closed'
        run: uv run --all-extras --group docs mkdocs build --clean

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site
